### ISSUE TITLE
Dealing with endianness?

### ISSUE THREAD

**Issue by yifu** [HewlettPackard/structex#1]
When I'm using `binary/encoding` this library processes endianness issues. As in [this exemple](https://pkg.go.dev/encoding/binary#example-Read).

Is it planned to implement such mechanism for [u]int16, [u]int32, [u]int64?

**Comment by NateThornton** [comment]
I don't fully understand your question. Can you maybe provide a test case or code snippet for your use case?

Current implementation assumes little-endian. Are you asking if big-endian can be supported? If that's the case, then yes I can work on big-endian support.

**Comment by yifu** [comment]
> Current implementation assumes little-endian. Are you asking if big-endian can be supported? 

Yes that is what I am asking for. :)

**Comment by NateThornton** [comment]
Sure, I can work on adding big-endian. I will add new endian options 'little' or 'big' similar to what is done by https://github.com/lunixbochs/struc#endian-formats.
